### ISSUE TITLE
Delete-Key does not delete Traders

### ISSUE THREAD

**Issue by PascalRombach** [HHG-TecLap/troedelmarkt#4]
# Brief
Pressing the "Delete" key on the keyboard does not delete traders in the trader view.

# Steps to reproduce this bug
1. Set up a working server and launch and connect the client
2. Go to the trader view
3. Create a trader if not existing
4. Select a trader
5. Press the "Delete" key
6. Refresh the trader view

# Expected behaviour
After step 5 the dialogue for deleting a trader should appear

# Exhibited behaviour
The trader is not deleted, though it disappears in the data grid. Refreshing the trader list causes the trader to reappear.

**Comment by albrechtf0** [comment]
Problem could not be solved easily. Instead the feature for deleting traders using the delete-key has been removed enitely.
