### ISSUE TITLE
Ignore empty transaction items when finishing transaction

### ISSUE THREAD

**Issue by jateute** [HHG-TecLap/troedelmarkt#5]
When finishing the transaction empty transaction items don't get ignored, which would be better for convienence and faster when using the software, because you wouldn't need to delete the last item when using the enter feature

**Comment by PascalRombach** [comment]
When they say traders they mean transaction items
(Edited because misgendering; sorry ^^')

**Comment by jateute** [comment]
Changed to transaction items

**Comment by albrechtf0** [comment]
Transaction items are now ignored in the frontend when sending a transaction
